## API KEYS
SGIS_consumer_key: '8276662061b14b5f987a'
SGIS_consumer_secret: '14421a5c1fcc47138af3'
ors_token: '5b3ce3597851110001cf62489088dae14da4439c9c32b3bf6df4cb06'

## File Paths
od_data_path: './od_data'
stay_data_path: './stay_data'
dong_code_path: './data_info/KIKmix_20230701.csv'
save_directory: './results'
error_directory: './errors'

## Data Selection
date: '0910'
destination: '서울특별시 서대문구 성산로 370'
view_all_day: False
time: '12:00'

## Coordinate Creation
probability: 0.8

## Operation Options
coordinates_only: False
coordinates_path: 'results/서울특별시서대문구성산로370_D0910_T12:00_P0.8/coordinates/coordinates.json'